import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="top-bar">
          <h1 className="top-header">Kitchen</h1>
          <div className="top-list">
            <button>All</button>
            <button>Freezer</button>
            <button>Fridge</button>
            <button>Pantry</button>
          </div>
        </nav>
        {children}
        <nav className="nav-bar">
          <ul className="nav-list">
            <li className="nav-img">
              <img src="/assets/recipe.png" alt="" />
              <a className="nav-link" href=""></a>
            </li>
            <li className="nav-img">
              <img src="/assets/recipe.png" alt="" />
              <a className="nav-link" href=""></a>
            </li>
            <li className="nav-img">
              <img src="/assets/recipe.png" alt="" />
              <a className="nav-link" href=""></a>
            </li>
            <li className="nav-img">
              <img src="/assets/recipe.png" alt="" />
              <a className="nav-link" href=""></a>
            </li>
          </ul>
        </nav>
      </body>
    </html>
  );
}
